<?php

namespace App\Controller\Admin;

use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\ArrayField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ChoiceField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use function Symfony\Bridge\Doctrine\Form\Type\DoctrineType;

class UserCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return User::class;
    }

    //----TENTER DE GERER LE HASH DES MDP
    /*    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
        {
            parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
        }

        public function __construct(UserPasswordHasherInterface $hasheur){
            $hasheur ->hashPassword();
            $this->persistEntity();
        }*/


    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('username'),
            ArrayField::new('Roles'),
            TextField::new('nom'),
            TextField::new('prenom'),
            TextField::new('email'),
            //ChoiceField::new('roles'),

            //TextEditorField::new('description'),
        ];
    }

}
